#spring.application.name=projspring
#spring.datasource.url=jdbc:postgresql://localhost:5432/projspring_db
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=postgrespw
#logging.level.org.springframework.security=DEBUG
#server.port=8081
#
##spring.jpa.defer-datasource-initialization=true
##spring.jpa.hibernate.ddl-auto=create
##spring.sql.init.mode=always
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=never


# DATABASE CONFIGURATION
# We use the ${VARIABLE:default} syntax so it works both locally and in the cloud
spring.datasource.url=${JDBC_URL:jdbc:postgresql://localhost:5432/projspring_db}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:postgrespw}
spring.datasource.driverClassName=org.postgresql.Driver

# SERVER CONFIGURATION
# Railway assigns a random PORT for every deployment
server.port=${PORT:8081}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true